= SDI (Container Image) Registry
Michal Minář
:toc:

The secure container image registry suitable for hosting SAP Data Intelligence (SDI from now on)
images on OpenShift cluster.

The word "secured" means that the communication is encrypted using a TLS. If the registry is also
exposed publicly, it must require authentication and authorization in order to pull SAP images.

The registry will be referred to throughout this document as SDI Registry.

== Deployment

SDI Registry's kubernetes resources are defined in OpenShift Templates. To choose the right template
and provide the right parameters for it, it is recommended to use the link:../deploy-registry.sh[]
script.

=== Prerequisites

. OCP cluster must be healthy including all the cluster operators.
. _(`ubi-build` or `custom-build` flavours)_The
  link:https://docs.openshift.com/container-platform/4.6/registry/configuring-registry-operator.html[OCP
  integrated image registry] must be properly configured and working.
. _(`ubi-build` flavour)_ Pull secret for the registry.redhat.io must be configured. 
. `jq >= 1.6` binary available on the management host

=== Template flavours

There are three different OCP templates designed for different scenarios:

[[template-flavours]]
[width="100%",cols="17%,35%,48%",options="header",]
|===
|Flavour | Template file| Description
|`ubi-build` | link:./ocp-template.json[] | (_recommended_, _connected_, _default_) To be used in
connected OCP clusters. A local build of SDI Registry will be performed using UBI8 as the base
image.

|`ubi-prebuilt` | link:./ocp-prebuilt-image-template.json[] | (_disconnected_) To be used in
disconnected/offline/air-gapped OCP clusters. The image must be first mirrored to a local
registry (other than SDI Registry).

|`custom-build` | link:./ocp-custom-source-image-template.json[] | For non-production, it is
possible to use a custom base image (e.g. CentOS). A very limited or no support will be offered in
case of issues though.
|===

The flavour shall be passed as `--flavour` parameter to the link:./deploy-registry.sh[] script.

=== Ensuring Red Hat registry pull secret

In order to use `ubi-build` flavour, you must have the pull secret.

. Get a secret for accessing registry.redhat.io at
  link:https://access.redhat.com/terms-based-registry/[Red Hat Registry Service Accounts]. See
  link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication]
  for more information.
. Make it available on your management host. Let's assume the file name
  `rht-registry-username-secret.yaml`.

[[tmpl-run]]
=== Template instantiation

==== Generic instantiation for a connected environment

. Make the git repository available on your management host.
+
....
# git clone https://github.com/redhat-sap/sap-data-intelligence
....
+
. Inspect the available arguments of the deployment script:
+
....
# ./sap-data-intelligence/registry/deploy-registry.sh --help
....
+
. Choose the right set of arguments and make a dry run to see what will happen:
+
....
# ./sap-data-intelligence/registry/deploy-registry.sh --flavour=ubi-build \
    --rp ./rht-registry-username-secret.yaml --dry-run
....
+
. Next time, deploy the SDI registry for real and wait until it gets deployed:
+
....
# ./sap-data-intelligence/registry/deploy-registry.sh --flavour=ubi-build \
    --rp ./rht-registry-username-secret.yaml --wait
....

==== Generic instantiation for a disconnected environment

There must be another container image registry running outside of the OpenShift cluster to host
the image of SDI Registry. That registry should be used to host SAP Data Intelligence images also
as long as it is compatible. Otherwise, please follow this guide.

. Mirror the pre-built image of SDI Registry to the local registry. For example, on RHEL8:
** Where the management host has access to the internet:
+
....
# podman login local.image.registry:5000    # if the local registry requires authentication
# skopeo copy \
    docker://quay.io/redhat-sap-cop/container-image-registry:latest \
    docker://local.image.registry:5000/container-image-registry:latest
....
+
** Where the management host _lacks_ access to the internet.
... Copy the image on a USB flash on a host having the connection to the internet:
+
....
# skopeo copy \
    docker://quay.io/redhat-sap-cop/contaimer-image-registry:latest \
    oci-archive:/var/run/user/1000/usb-disk/container-image-registry:latest
....
+
... Plug the USB drive to the management host and mirror the image from it to your
    `local.image.registry:5000`:
+
....
# skopeo copy \
    oci-archive:/var/run/user/1000/usb-disk/container-image-registry:latest \
    docker://local.image.registry:5000/container-image-registry:latest
....
. Make the git repository available on your management host.
+
....
# git clone https://github.com/redhat-sap/sap-data-intelligence
....
+
. Inspect the available arguments of the deployment script:
+
....
# ./sap-data-intelligence/registry/deploy-registry.sh --help
....
+
. Choose the right set of arguments and make a dry run to see what will happen. Make sure to
  choose `ubi-prebuilt` flavour and use the right image pull specification:
+
....
# ./sap-data-intelligence/registry/deploy-registry.sh --flavour=ubi-prebuilt \
    --image-pull-spec=local.image.registry:5000/container-image-registry:latest --dry-run
....
+
. Next time, deploy the SDI Registry for real and wait until it gets deployed:
+
....
# ./sap-data-intelligence/registry/deploy-registry.sh --flavour=ubi-prebuilt \
    --image-pull-spec=local.image.registry:5000/container-image-registry:latest --wait
....
+
. Please make sure to backup the arguments used for future updates.

== Update instructions

So far, updates need to be performed manually.

Please follow the steps outlined in xref:#tmpl-run[Template Instantiation] anew. A re-run of the
deployment script will change only what needs to be changed.

== Post configuration and verification

=== Making SDI Registry trusted

By default, the SDI Registry is secured by the Ingress Controller's certificate signed by a
self-signed CA certificate. Self-signed certificates are trusted neither by OpenShift nor by SDI.

If the registry is signed by a proper trusted (not self-signed) certificate, this may be skipped.

==== Making registry trusted in OpenShift

By default, the CA certificate used by Ingress Controller is available in the secret router-ca in openshift-ingress-operator namespace.

Set registry's namespace into the `nm` variable and execute the following code in bash:

    # nm="sdi-registry"   # namespace where registry runs
    # registry="$(oc get route -n "$nm" \
        container-image-registry -o jsonpath='{.spec.host}')"; \
      caBundle="$(oc get -n openshift-ingress-operator -o json secret/router-ca | \
        jq -r '.data as $d | $d | keys[] | select(test("\\.(?:crt|pem)$")) | $d[.] | @base64d')"; \
      cmName="$(oc get images.config.openshift.io/cluster -o json | \
        jq -r '.spec.additionalTrustedCA.name // "trusted-registry-cabundles"')"; \
      if oc get -n openshift-config "cm/$cmName" 2>/dev/null; then
        # configmap already exists -> just update it
        oc get -o json -n openshift-config "cm/$cmName" | \
            jq '.data["'"${registry//:/..}"'"] |= "'"$caBundle"'"' | \
            oc replace -f - --force
      else
          # creating the configmap for the first time
          oc create configmap -n openshift-config "$cmName" \
              --from-literal="${registry//:/..}=$caBundle"
          oc patch images.config.openshift.io cluster --type=merge \
              -p '{"spec":{"additionalTrustedCA":{"name":"'"$cmName"'"}}}'
      fi

==== Making registry trusted in SAP Data Intelligence

The self-signed CA certificate of Ingress Controller must be
link:https://help.sap.com/viewer/b13b5722c8ff4bf9bb097251310031d0/3.2.latest/en-US/95b577f233ea4546ac7620b607fd1f70.html[imported
to each SDI tenant using Connection Manager]. Just the `default` tenant is the exception from this
rule. The import for this tenant happens automatically during the installation as long as
link:https://help.sap.com/viewer/a8d90a56d61a49718ebcb5f65014bbe7/3.2.latest/en-US/39e8e391d5984e919725e601f089db74.html?q=cmcertificates[cmcertificates
secret is configured correctly]. That can be done by link:../observer/README.adoc[SDI Observer] as long as the
`INJECT_CABUNDLE` is set to `true`.


=== Determine Registry's credentials

The username and password are separated by a colon in the `SDI_REGISTRY_HTPASSWD_SECRET_NAME`
secret:

....
# # make sure to change the "sdi-registry" to your SDI Registry's namespace 
# oc get -o json -n "sdi-registry" secret/container-image-registry-htpasswd | \
    jq -r '.data[".htpasswd.raw"] | @base64d'
user-qpx7sxeei:OnidDrL3acBHkkm80uFzj697JGWifvma
....

=== Verification

. Obtain Ingress' default self-signed CA certificate:
+
....
# oc get secret -n openshift-ingress-operator -o json router-ca | \
    jq -r '.data as $d | $d | keys[] | select(test("\\.crt$")) | $d[.] | @base64d' >router-ca.crt
....
+
. Set the `nm` variable to the Kubernetes namespace where SDI Registry runs:
+
....
# nm=sdi-registry
....
+
. Do a simple test using curl:
+
....
# # determine registry's hostname from its route
# hostname="$(oc get route -n "$nm" container-image-registry -o jsonpath='{.spec.host}')"
# curl -I --user user-qpx7sxeei:OnidDrL3acBHkkm80uFzj697JGWifvma --cacert router-ca.crt \
    "https://$hostname/v2/"
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Date: Sun, 24 May 2020 17:54:31 GMT
Set-Cookie: d22d6ce08115a899cf6eca6fd53d84b4=9176ba9ff2dfd7f6d3191e6b3c643317; path=/; HttpOnly; Secure
Cache-control: private
....
+
. Optionally, make the certificate trusted on you management host (this example is for RHEL7 or
  newer):
+
....
# sudo cp -v router-ca.crt /etc/pki/ca-trust/source/anchors/router-ca.crt
# sudo update-ca-trust
....
+
. Using the podman:
+
....
# # determine registry's hostname from its route
# hostname="$(oc get route -n "$nm" container-image-registry -o jsonpath='{.spec.host}')"
# sudo mkdir -p "/etc/containers/certs.d/$hostname"
# sudo cp router-ca.crt "/etc/containers/certs.d/$hostname/"
# podman login -u user-qpx7sxeei "$hostname"
Password:
Login Succeeded!
....
