# permissions for end users to edit sdiobservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sdiobserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: observer-operator
    app.kubernetes.io/part-of: observer-operator
    app.kubernetes.io/managed-by: kustomize
  name: sdiobserver-editor-role
rules:
- apiGroups:
  - sdi.sap-redhat.io
  resources:
  - sdiobservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sdi.sap-redhat.io
  resources:
  - sdiobservers/status
  verbs:
  - get
