apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sdi-node-configurator
  namespace: sdi-observer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sdi-node-configurator
subjects:
  - kind: ServiceAccount
    name: sdi-node-configurator
    namespace: sdi-observer