apiVersion: sdi.sap-redhat.io/v1alpha1
kind: SDIObserver
metadata:
  labels:
    app.kubernetes.io/name: sdiobserver
    app.kubernetes.io/instance: sdiobserver-sample
    app.kubernetes.io/part-of: observer-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: observer-operator
  name: sdiobserver-sample
  # namespace: sdi-observer
spec:
  # TODO(user): Add fields here
  sdiRoute:
    namespace: sdi
    targetedService: vsystem
  slcbRoute:
    namespace: sap-slcbridge
    targetedService: slcbridgebase-service

